2020-04-02 03:29:00,189 DEBUG   MainThread:28171 [wandb_config.py:_load_defaults():122] no defaults not found in config-defaults.yaml
2020-04-02 03:29:00,230 DEBUG   MainThread:28171 [meta.py:setup():97] code probe starting
2020-04-02 03:29:00,233 DEBUG   MainThread:28171 [meta.py:_setup_code_git():49] probe for git information
2020-04-02 03:29:00,252 DEBUG   MainThread:28171 [meta.py:_setup_code_program():58] save program starting
2020-04-02 03:29:00,252 DEBUG   MainThread:28171 [meta.py:_setup_code_program():60] save program starting: /home/tmarcu/brain2brain/brain2brain/__main__.py
2020-04-02 03:29:00,256 DEBUG   MainThread:28171 [meta.py:_setup_code_program():65] save program saved: /home/tmarcu/brain2brain/tcn_experiment_m2o_2/wandb/dryrun-20200402_072859-woc9txns/code/brain2brain/__main__.py
2020-04-02 03:29:00,256 DEBUG   MainThread:28171 [meta.py:_setup_code_program():67] save program
2020-04-02 03:29:00,258 DEBUG   MainThread:28171 [meta.py:setup():119] code probe done
2020-04-02 03:29:00,270 DEBUG   MainThread:28171 [run_manager.py:__init__():545] Initialized sync for brain2brain/woc9txns
2020-04-02 03:29:00,274 INFO    MainThread:28171 [run_manager.py:wrap_existing_process():1148] wrapping existing process 28106
2020-04-02 03:29:01,198 INFO    Thread-3  :28171 [run_manager.py:_on_file_modified():692] file/dir modified: /home/tmarcu/brain2brain/tcn_experiment_m2o_2/wandb/dryrun-20200402_072859-woc9txns/config.yaml
2020-04-02 03:29:06,780 INFO    MainThread:28171 [run_manager.py:init_run():928] system metrics and metadata threads started
2020-04-02 03:29:06,780 INFO    MainThread:28171 [run_manager.py:wrap_existing_process():1165] informing user process we are ready to proceed
2020-04-02 03:29:06,780 INFO    MainThread:28171 [run_manager.py:_sync_etc():1272] entering loop for messages from user process
2020-04-02 03:39:45,491 INFO    MainThread:28171 [run_manager.py:_sync_etc():1295] received message from user process: {"save_policy": {"glob": "wandb.h5", "policy": "live"}}
2020-04-02 03:39:45,491 INFO    MainThread:28171 [run_manager.py:_sync_etc():1295] received message from user process: {"exitcode": 0}
2020-04-02 03:39:45,491 INFO    MainThread:28171 [run_manager.py:_sync_etc():1381] closing log streams and sending exitcode to W&B
2020-04-02 03:39:45,492 INFO    MainThread:28171 [run_manager.py:shutdown():1072] shutting down system stats and metadata service
20-04-02 03:39:45,491 INFO    MainThread:28171 [woc9txns:run_manager.py:_sync_etc():1381] closing log streams and sending exitcode to W&B
2020-04-02 03:39:45,492 INFO    MainThread:28171 [woc9txns:run_manager.py:shutdown():1072] shutting down system stats and metadata service
